### ISSUE TITLE
Need a new release including a fix for Python 3

### ISSUE THREAD

**Issue by vstinner** [kgrandis/nose-exclude#3]
Hi,

I'm working on the OpenStack Horizon project. "tox -e py34" runs django_test ("manage.py test") which runs nose. The problem is that nose-exclude is not compatible with Python 3: wantMethod() always return False because test.im_class attribute doesn't exist.

Good news: the bug was already fixed almost 2 months ago in the commit 0717e443fdacb94cb0c590431f0b222fd715bffe.

Would it be possible to get a release including this fix please?

Background: https://bitbucket.org/kgrandis/nose-exclude/issues/10/test-failures-with-python-3

Victor

**Comment by kgrandis** [comment]
committed, tagged, and pushed to PyPI:

https://travis-ci.org/kgrandis/nose-exclude
https://pypi.python.org/pypi/nose-exclude/0.4.0

**Comment by vstinner** [comment]
Wow! Thanks a lot for the super quick release!

**Comment by philfreo** [comment]
@kgrandis Could you add the proper classifier to setup.py so that https://caniusepython3.com/project/nose-exclude knows Python 3 is supported?
